name: CI

# 1. Uruchamiaj na pull_request i push do main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Pobranie kodu z repozytorium
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Ustawienie wersji Pythona
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instalacja zależności (opcjonalna – np. do uruchomienia testów wewnątrz środowiska GH)
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      # 4. Krok testów – symbolicznie używamy "echo"
      - name: Run tests
        run: echo "Test"

      # 5. Zalogowanie do DockerHub (tylko przy push do main)
      - name: Log in to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 6. Budowanie obrazu Dockera
      - name: Build Docker image
        run: docker build -t my-django-app .

      # 7. Tagi obrazu i push do DockerHub (tylko przy push do main)
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          # Ustal, gdzie chcesz wrzucić obraz – np. "docker.io/<twoja_nazwa>/my-django-app"
          docker tag my-django-app ${{ secrets.DOCKERHUB_USERNAME }}/my-django-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-django-app:latest
